# Generated by Django 2.2 on 2019-04-20 12:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190420_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=blog.models.update_filename),
        ),
    ]
